project-metadata:
    group: ma.wayfare

services:
    config-server:
        port: 8888
        host: config-server
    rabbitmq:
        port: 5672
        management-port: 15672
        host: rabbitmq
        username: guest
        password: guest
        queue-name: notification_queue
        json-queue-name: notification_json_queue
        exchange-name: notification_exchange
        routing-key: notification_routing_key
        json-routing-key: notification_json_routing_key
    assistant:
        port: 5000
        host: assistant
    gateway:
        port: 8080
        host: gateway
    auth:
        port: 8081
        host: auth
    user:
        port: 8082
        host: user
    trip:
        port: 8084
        host: trip
        db:
            url: jdbc:postgresql://postgres:5432/trip_management?createDatabaseIfNotExist=true
            username: postgres
            password: postgres
    geolocation:
        port: 8085
        host: geolocation
    notification:
        port: 8086
        host: notification
        db:
            url: jdbc:mysql://mysql:3306/wayfare_notifications?createDatabaseIfNotExist=true
            username: root
            password: password
            driver: com.mysql.cj.jdbc.Driver