project-metadata:
    group: ma.wayfare

services:
    config:
        port: 8888
        host: localhost
    gateway:
        port: 8080
        host: localhost
    auth:
        port: 8081
        host: localhost
    user:
        port: 8082
        host: localhost
    ticket:
        port: 8083
        host: localhost
    route-schedule:
        port: 8084
        host: localhost
    bus-geolocation:
        port: 8085
        host: localhost
    notification:
        port: 8086
        host: localhost
        db:
            host: localhost
            port: 3306
            username: root
            password: password
            database: wayfare_notifications
            driver: com.mysql.cj.jdbc.Driver
            dialect: org.hibernate.dialect.MySQL5Dialect
    rabbitmq:
        port: 5672
        management-port: 15672
        host: localhost
        username: guest
        password: guest
        queue-name: notification_queue
        json-queue-name: notification_json_queue
        exchange-name: notification_exchange
        routing-key: notification_routing_key
        json-routing-key: notification_json_routing_key